### ISSUE TITLE
add discussion to blog post

### ISSUE THREAD

**Issue by jcolomb** [noamross/noamross.net#2]
Hi,

nice website!
I was wondering if you got a way to discuss things on the blog. For instance if I would like to ask why you used circleci and not netify, a commenting section would be useful...

people usually integrate disqus.

**Comment by noamross** [comment]
Thanks! I never found blog comments that useful myself - they tend to attract trolls and spammers. 
Also one of my goals for this site was to avoid using third-party services that harvest user data.  Disqus and similar third-party solutions inject a lot of user-tracking javascript. I don't use Google Analytics for the same reason.  I considered https://utteranc.es/, but it doesn't allow for custom styling and you might have noticed I'm extremely picky about that.  If you know of another commenting solution, let me know, I'll consider it! But for now I'm fine with people just asking me things on here or Twitter.

But to answer your question, Netlify doesn't support R, while CircleCI lets me run anything I have a Docker container for.  Also, Netlify does build-deploy-host, and I only need CI for build-deploy.  I like my host, nearlyfreespeech.net, because they give me low-level control like SSH access to the server and the ability to use .htaccess to control site access and redirects.  So I use CircleCI to build and then deploy to nearlyfreespeech.

**Comment by jcolomb** [comment]
thanks for the answer. utterances seems quite nice, although github is the third party there ;)

You may have a look into the https://dokie.li/ project. In theory it should be working, but it needs quite a lot of tweaking and I was not able to get it working. But probably you can.
